//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Game.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace PaddleInputs
{
    public partial class @PaddleInput : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @PaddleInput()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""Game"",
    ""maps"": [
        {
            ""name"": ""Game"",
            ""id"": ""78008438-5d93-44f7-a9d7-1092ecbcdf72"",
            ""actions"": [
                {
                    ""name"": ""PaddleLeft"",
                    ""type"": ""Button"",
                    ""id"": ""df248d21-8176-49a4-80a1-125c06e847d8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PaddleRight"",
                    ""type"": ""Button"",
                    ""id"": ""401a285f-63f7-4101-b059-88736d3cbd3a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""07d775b3-fdee-4587-b3cd-a792f12120e9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PaddleLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""58935a2a-9b4a-4cbf-a3cb-38363d4219bb"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PaddleRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Game
            m_Game = asset.FindActionMap("Game", throwIfNotFound: true);
            m_Game_PaddleLeft = m_Game.FindAction("PaddleLeft", throwIfNotFound: true);
            m_Game_PaddleRight = m_Game.FindAction("PaddleRight", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Game
        private readonly InputActionMap m_Game;
        private IGameActions m_GameActionsCallbackInterface;
        private readonly InputAction m_Game_PaddleLeft;
        private readonly InputAction m_Game_PaddleRight;
        public struct GameActions
        {
            private @PaddleInput m_Wrapper;
            public GameActions(@PaddleInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @PaddleLeft => m_Wrapper.m_Game_PaddleLeft;
            public InputAction @PaddleRight => m_Wrapper.m_Game_PaddleRight;
            public InputActionMap Get() { return m_Wrapper.m_Game; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(GameActions set) { return set.Get(); }
            public void SetCallbacks(IGameActions instance)
            {
                if (m_Wrapper.m_GameActionsCallbackInterface != null)
                {
                    @PaddleLeft.started -= m_Wrapper.m_GameActionsCallbackInterface.OnPaddleLeft;
                    @PaddleLeft.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnPaddleLeft;
                    @PaddleLeft.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnPaddleLeft;
                    @PaddleRight.started -= m_Wrapper.m_GameActionsCallbackInterface.OnPaddleRight;
                    @PaddleRight.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnPaddleRight;
                    @PaddleRight.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnPaddleRight;
                }
                m_Wrapper.m_GameActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @PaddleLeft.started += instance.OnPaddleLeft;
                    @PaddleLeft.performed += instance.OnPaddleLeft;
                    @PaddleLeft.canceled += instance.OnPaddleLeft;
                    @PaddleRight.started += instance.OnPaddleRight;
                    @PaddleRight.performed += instance.OnPaddleRight;
                    @PaddleRight.canceled += instance.OnPaddleRight;
                }
            }
        }
        public GameActions @Game => new GameActions(this);
        public interface IGameActions
        {
            void OnPaddleLeft(InputAction.CallbackContext context);
            void OnPaddleRight(InputAction.CallbackContext context);
        }
    }
}
